REG_TL_ID = "registrations-tl"
SLD_ID = "date-slider"
TOOLS_GRAPH_ID = "tools-graph"
MARKETPLACE_GRAPH_ID = "marketplace-graph"

DATAEXP_DIR = "../DataExports"
EVENT_FLNM = "events"
CNTMGMT_KEY = "cntmgmt"
TOOLS_KEY = "tools"
MARKETPLACE_KEY = "marketplace"
